sudo: false

language: node_js

node_js:
  - '6'
  - lts/*

cache:
  directories:
    - node_modules

before_install:
  - npm install -g typescript ts-node

install: npm install

script:
  - npm run testb
  - npm run test:types
